name: Deploy Sphinx documentation to Pages

on:
  push:
    branches:
      - dunnack/sphinx-to-github-pages
      - main
    paths:
      - .github/workflows/gh-pages.yaml
      - docs/**

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - id: deployment
        uses: sphinx-notes/pages@6e3e0108e79636a0908b1c2c5899e0d3dfad0bc1 # 3.6
        with:
          checkout: false
          documentation_path: docs
          requirements_path: docs/requirements.txt
