name: Deploy Sphinx documentation to Pages

on:
  push:
    branches:
      - dunnack/sphinx-to-github-pages
      - main
    paths:
      - .github/workflows/gh-pages.yaml
      - docs/**

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - id: deployment
        uses: sphinx-notes/pages@e9c8f79f285fb41a150ba6e08a3c2a29635e7ee1 # 3.5
        with:
          checkout: false
          documentation_path: docs
          requirements_path: docs/requirements.txt
